# This is a basic workflow to help you get started with Actions

name: dbms-tests

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - 'dev*' 
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  compile-run:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    timeout-minutes: 2
    strategy:
      matrix:
        compiler:
          - command: g++-10
            flags:
          - command: clang++-10
            flags: -stdlib=libstdc++
          - command: clang++-10
            flags: -stdlib=libc++
        sanitize:
          - flags: -fsanitize=undefined
            run-prefix: valgrind --quiet --leak-check=full --error-exitcode=123
          - flags: -fsanitize=undefined -fsanitize=address
            run-prefix:
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - run: cmake --version
      - run: cmake . -DCMAKE_CXX_COMPILER="${{matrix.compiler.command}}" -DCMAKE_CXX_FLAGS="${{matrix.compiler.flags}} ${{matrix.sanitize.flags}}"
      - run: make
